dashboard_admin:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: AdminBundle:Admin:index }

list_owner_admin:
    locales:
        en: "/owner/list"
        fr: "/proprio/liste"
    defaults: { _controller: AdminBundle:Admin:listOwner }
add_owner_admin:
    locales:
        en: "/owner/add"
        fr: "/proprio/ajouter"
    defaults: { _controller: AdminBundle:Admin:addOwner }
edit_owner_admin:
    locales:
        en: "/owner/edit"
        fr: "/proprio/editer"
    defaults: { _controller: AdminBundle:Admin:editOwner }

list_admin:
    locales:
        en: "/admin/list"
        fr: "/admin/liste"
    defaults: { _controller: AdminBundle:Admin:listAdmin }

remove_admin:
    locales:
        en: "/remove-admin"
        fr: "/supprimer-admin"
    defaults: { _controller: AdminBundle:Admin:removeFromAdmin }

add_admin:
    locales:
        en: "/add-admin"
        fr: "/ajouter-admin"
    defaults: { _controller: AdminBundle:Admin:addAdmin }
edit_admin:
    locales:
        en: "/edit-admin"
        fr: "/editer-admin"
    defaults: { _controller: AdminBundle:Admin:editAdmin }

list_offer_admin:
    locales:
        en: "/offer/list"
        fr: "/offre/liste"
    defaults: { _controller: AdminBundle:Admin:listOffer }

change_validation_status:
    locales:
        en: "/change-validation-status"
        fr: "/changer-status-validation"
    defaults: { _controller: AdminBundle:Admin:changeValidationStatus }

log_page:
    locales:
        en: "/log-page"
        fr: "/page-stat"
    defaults: { _controller: AdminBundle:Admin:logPage }

list_ad_admin:
    locales:
        en: "/ad/list/{archived}"
        fr: "/pub/liste/{archived}"
    defaults: { _controller: AdminBundle:Ad:listAd }

create_ad:
    locales:
        en: "/ad/create"
        fr: "/pub/creation"
    defaults: { _controller: AdminBundle:Ad:create }

edit_ad:
    locales:
        en: "/ad/edit"
        fr: "/pub/edition"
    defaults: { _controller: AdminBundle:Ad:edit }
archive_ad:
    locales:
        en: "/ad/archive"
        fr: "/pub/archiver"
    defaults: { _controller: AdminBundle:Ad:archive }