<?php

namespace AppBundle\Repository;

/**
 * OwnershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnershipRepository extends \Doctrine\ORM\EntityRepository
{
}
