#    ai_mysyndic.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
  app.user_register:
      class: AppBundle\Service\RegisterUser
      arguments: ['@fos_user.user_manager','@security.token_storage','@session']

  app.offer_generate_url:
        class: AppBundle\Service\GenerateUrl
        arguments: ['@translator']
  app.redirect.after.login:
        class: AppBundle\Service\AfterLoginRedirect
        arguments: ['@router']
  app.owner_image:
        class: AppBundle\Service\Namer
        tags:
          - { name: namer }
  app.find_latlong:
      class: AppBundle\Service\FindLatLong






